//
// CharacterPositionType.cs
//
// This file was generated by XMLSpy 2011r3sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace LA_CAS_Messages
{

	public class CharacterPositionType : SchemaInt
	{

		public CharacterPositionType() : base()
		{
		}

		public CharacterPositionType(string newValue) : base(newValue)
		{
			Validate();
		}

		public CharacterPositionType(SchemaInt newValue) : base(newValue)
		{
			Validate();
		}

		public  void Validate()
		{

			if (CompareTo(GetMinInclusive()) < 0)
				throw new System.Exception("Value of CharacterPositionType is out of range.");
		}
		public  SchemaInt GetMinInclusive()
		{
			return new SchemaInt("1");
		}
	}
}
