//
// RequestMemorableWordCharsRequestType.cs
//
// This file was generated by XMLSpy 2011r3sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using Altova.Types;

namespace LA_CAS_Messages
{
	public class RequestMemorableWordCharsRequestType : Altova.Xml.Node
	{
		#region Forward constructors

		public RequestMemorableWordCharsRequestType() : base() { SetCollectionParents(); }

		public RequestMemorableWordCharsRequestType(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public RequestMemorableWordCharsRequestType(XmlNode node) : base(node) { SetCollectionParents(); }
		public RequestMemorableWordCharsRequestType(Altova.Xml.Node node) : base(node) { SetCollectionParents(); }
		public RequestMemorableWordCharsRequestType(Altova.Xml.Document doc, string namespaceURI, string prefix, string name) : base(doc, namespaceURI, prefix, name) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{

		    for (	XmlNode DOMNode = GetDomFirstChild( NodeType.Element, "", "UCRN" );
					DOMNode != null; 
					DOMNode = GetDomNextChild( NodeType.Element, "", "UCRN", DOMNode )
				)
			{
				InternalAdjustPrefix(DOMNode, false);
			}

		    for (	XmlNode DOMNode = GetDomFirstChild( NodeType.Element, "", "UserID" );
					DOMNode != null; 
					DOMNode = GetDomNextChild( NodeType.Element, "", "UserID", DOMNode )
				)
			{
				InternalAdjustPrefix(DOMNode, false);
			}
		}

		public void SetXsiType()
		{
 			XmlElement el = (XmlElement) domNode;
			el.SetAttribute("type", "http://www.w3.org/2001/XMLSchema-instance", "RequestMemorableWordCharsRequest");
		}


		#region UCRN accessor methods
		public static int GetUCRNMinCount()
		{
			return 1;
		}

		public static int UCRNMinCount
		{
			get
			{
				return 1;
			}
		}

		public static int GetUCRNMaxCount()
		{
			return 1;
		}

		public static int UCRNMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetUCRNCount()
		{
			return DomChildCount(NodeType.Element, "", "UCRN");
		}

		public int UCRNCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "UCRN");
			}
		}

		public bool HasUCRN()
		{
			return HasDomChild(NodeType.Element, "", "UCRN");
		}

		public core3.UCRNType NewUCRN()
		{
			return new core3.UCRNType();
		}

		public core3.UCRNType GetUCRNAt(int index)
		{
			return new core3.UCRNType(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "UCRN", index)));
		}

		public XmlNode GetStartingUCRNCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "UCRN" );
		}

		public XmlNode GetAdvancedUCRNCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "UCRN", curNode );
		}

		public core3.UCRNType GetUCRNValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new core3.UCRNType( curNode.InnerText );
		}


		public core3.UCRNType GetUCRN()
		{
			return GetUCRNAt(0);
		}

		public core3.UCRNType UCRN
		{
			get
			{
				return GetUCRNAt(0);
			}
		}

		public void RemoveUCRNAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "UCRN", index);
		}

		public void RemoveUCRN()
		{
			RemoveUCRNAt(0);
		}

		public XmlNode AddUCRN(core3.UCRNType newValue)
		{
			if( newValue.IsNull() == false )
				return AppendDomChild(NodeType.Element, "", "UCRN", newValue.ToString());
			return null;
		}

		public void InsertUCRNAt(core3.UCRNType newValue, int index)
		{
			if( newValue.IsNull() == false )
				InsertDomChildAt(NodeType.Element, "", "UCRN", index, newValue.ToString());
		}

		public void ReplaceUCRNAt(core3.UCRNType newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "UCRN", index, newValue.ToString());
		}
		#endregion // UCRN accessor methods

		#region UCRN collection
        public UCRNCollection	MyUCRNs = new UCRNCollection( );

        public class UCRNCollection: IEnumerable
        {
            RequestMemorableWordCharsRequestType parent;
            public RequestMemorableWordCharsRequestType Parent
			{
				set
				{
					parent = value;
				}
			}
			public UCRNEnumerator GetEnumerator() 
			{
				return new UCRNEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class UCRNEnumerator: IEnumerator 
        {
			int nIndex;
			RequestMemorableWordCharsRequestType parent;
			public UCRNEnumerator(RequestMemorableWordCharsRequestType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.UCRNCount );
			}
			public core3.UCRNType  Current 
			{
				get 
				{
					return(parent.GetUCRNAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // UCRN collection

		#region UserID accessor methods
		public static int GetUserIDMinCount()
		{
			return 1;
		}

		public static int UserIDMinCount
		{
			get
			{
				return 1;
			}
		}

		public static int GetUserIDMaxCount()
		{
			return 1;
		}

		public static int UserIDMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetUserIDCount()
		{
			return DomChildCount(NodeType.Element, "", "UserID");
		}

		public int UserIDCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "UserID");
			}
		}

		public bool HasUserID()
		{
			return HasDomChild(NodeType.Element, "", "UserID");
		}

		public core3.UserIDType NewUserID()
		{
			return new core3.UserIDType();
		}

		public core3.UserIDType GetUserIDAt(int index)
		{
			return new core3.UserIDType(GetDomNodeValue(GetDomChildAt(NodeType.Element, "", "UserID", index)));
		}

		public XmlNode GetStartingUserIDCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "UserID" );
		}

		public XmlNode GetAdvancedUserIDCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "UserID", curNode );
		}

		public core3.UserIDType GetUserIDValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new core3.UserIDType( curNode.InnerText );
		}


		public core3.UserIDType GetUserID()
		{
			return GetUserIDAt(0);
		}

		public core3.UserIDType UserID
		{
			get
			{
				return GetUserIDAt(0);
			}
		}

		public void RemoveUserIDAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "UserID", index);
		}

		public void RemoveUserID()
		{
			RemoveUserIDAt(0);
		}

		public XmlNode AddUserID(core3.UserIDType newValue)
		{
			if( newValue.IsNull() == false )
				return AppendDomChild(NodeType.Element, "", "UserID", newValue.ToString());
			return null;
		}

		public void InsertUserIDAt(core3.UserIDType newValue, int index)
		{
			if( newValue.IsNull() == false )
				InsertDomChildAt(NodeType.Element, "", "UserID", index, newValue.ToString());
		}

		public void ReplaceUserIDAt(core3.UserIDType newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Element, "", "UserID", index, newValue.ToString());
		}
		#endregion // UserID accessor methods

		#region UserID collection
        public UserIDCollection	MyUserIDs = new UserIDCollection( );

        public class UserIDCollection: IEnumerable
        {
            RequestMemorableWordCharsRequestType parent;
            public RequestMemorableWordCharsRequestType Parent
			{
				set
				{
					parent = value;
				}
			}
			public UserIDEnumerator GetEnumerator() 
			{
				return new UserIDEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class UserIDEnumerator: IEnumerator 
        {
			int nIndex;
			RequestMemorableWordCharsRequestType parent;
			public UserIDEnumerator(RequestMemorableWordCharsRequestType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.UserIDCount );
			}
			public core3.UserIDType  Current 
			{
				get 
				{
					return(parent.GetUserIDAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // UserID collection

        private void SetCollectionParents()
        {
            MyUCRNs.Parent = this; 
            MyUserIDs.Parent = this; 
	}
}
}
