//
// SeoCitizenExpressInterestRequest_v0_1Doc.cs
//
// This file was generated by XMLSpy 2012sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;

namespace LA_CAS_Messages
{
	public class SeoCitizenExpressInterestRequest_v0_1Doc : Altova.Xml.Document
	{
		override protected void DeclareNamespaces(Altova.Xml.Node node)
		{
			DeclareNamespace(node, "core", "http://www.govtalk.gov.uk/core");
			DeclareNamespace(node, "AddressAndPersonalDetails", "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails");
			DeclareNamespace(node, "PersonDescriptives", "http://www.govtalk.gov.uk/people/PersonDescriptives");
			DeclareNamespace(node, "bs7666", "http://www.govtalk.gov.uk/people/bs7666");
			DeclareNamespace(node, "core", "http://www.scottishcitizen.gov.uk/citizen/core/v0-1");
			DeclareNamespace(node, "", "http://www.scottishcitizen.gov.uk/citizen/v0-1");
		}
	}
}
