//
// KnownFactValueType.cs
//
// This file was generated by XMLSpy 2011r3sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace LA_CAS_Messages.core3
{

	public class KnownFactValueType : SchemaString
	{

		public KnownFactValueType() : base()
		{
		}

		public KnownFactValueType(string newValue) : base(newValue)
		{
			Validate();
		}

		public KnownFactValueType(SchemaString newValue) : base(newValue)
		{
			Validate();
		}

		public  void Validate()
		{
		}
	}
}
