//
// WalkSortCodeType.cs
//
// This file was generated by XMLSpy 2012sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace LA_CAS_Messages.AddressAndPersonalDetails2
{

	public class WalkSortCodeType : SchemaString
	{
		public static  string[] sPatternValues = {
			"[0-9]{8}",
		};


		public WalkSortCodeType() : base()
		{
		}

		public WalkSortCodeType(string newValue) : base(newValue)
		{
			Validate();
		}

		public WalkSortCodeType(SchemaString newValue) : base(newValue)
		{
			Validate();
		}


		public static  int GetPatternCount()
		{
			return sPatternValues.Length;
		}

		public static  string GetPatternValue(int index)
		{
			return sPatternValues[index];
		}
		public  void Validate()
		{
		}
	}
}
