//
// CitizenQuerySubsetType.cs
//
// This file was generated by XMLSpy 2008r2sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace SeoListNotifications_v0_1.core3
{

	public class CitizenQuerySubsetType : SchemaString
	{
		public static  string[] sEnumValues = {
			"All",
			"Registered Only",
			"NonRegistered Only",
		};

		public  enum EnumValues
		{
			eAll = 0, /* All */
			eRegistered_Only = 1, /* Registered Only */
			eNonRegistered_Only = 2, /* NonRegistered Only */
			EnumValueCount
		};

		public CitizenQuerySubsetType() : base()
		{
		}

		public CitizenQuerySubsetType(string newValue) : base(newValue)
		{
			Validate();
		}

		public CitizenQuerySubsetType(SchemaString newValue) : base(newValue)
		{
			Validate();
		}

		public static  int GetEnumerationCount()
		{
			return sEnumValues.Length;
		}

		public static  string GetEnumerationValue(int index)
		{
			return sEnumValues[index];
		}

		public static  bool IsValidEnumerationValue(string val)
		{
			foreach (string s in sEnumValues)
			{
				if (val == s)
					return true;
			}
			return false;
		}

		public  void Validate()
		{

			if (!IsValidEnumerationValue(ToString()))
				throw new System.Exception("Value of CitizenQuerySubsetType is invalid.");
		}
	}
}
