//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace owsmtest.casuat
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.0.0.7070-dce2df4c")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SubmitMessageSoapHttp", Namespace="http://www.scottishcitizen.gov.uk/service")]
    public partial class CASEndpointBean : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        
        /// <remarks/>
        public CASEndpointBean()
        {
            this.Url = "http://owsm04.stirling.gov.uk:7777/gateway/services/SID0003001";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.scottishcitizen.gov.uk/service/sendCitizenAccountMessage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CitizenAccountResponseMessage", Namespace="http://www.scottishcitizen.gov.uk/service")]
        public CitizenAccountResponseMessage sendCitizenAccountMessage([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.scottishcitizen.gov.uk/service")] CitizenAccountRequestMessage CitizenAccountRequestMessage)
        {
            object[] results = this.Invoke("sendCitizenAccountMessage", new object[] {
                        CitizenAccountRequestMessage});
            return ((CitizenAccountResponseMessage)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendCitizenAccountMessage(CitizenAccountRequestMessage CitizenAccountRequestMessage, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("sendCitizenAccountMessage", new object[] {
                        CitizenAccountRequestMessage}, callback, asyncState);
        }
        
        /// <remarks/>
        public CitizenAccountResponseMessage EndsendCitizenAccountMessage(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CitizenAccountResponseMessage)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.0.0.7070-dce2df4c")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.scottishcitizen.gov.uk/service")]
    public partial class CitizenAccountRequestMessage
    {
        
        /// <remarks/>
        public CitizenAccountRequestType CASRequestData;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.0.0.7070-dce2df4c")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.scottishcitizen.gov.uk/service")]
    public partial class CitizenAccountRequestType
    {
        
        /// <remarks/>
        public CitizenAccountRequestHeaderType Header;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.0.0.7070-dce2df4c")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.scottishcitizen.gov.uk/service")]
    public partial class CitizenAccountRequestHeaderType
    {
        
        /// <remarks/>
        public string PartnerID;
        
        /// <remarks/>
        public string UserID;
        
        /// <remarks/>
        public string CorrelationID;
        
        /// <remarks/>
        public System.DateTime Timestamp;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.0.0.7070-dce2df4c")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.scottishcitizen.gov.uk/service")]
    public partial class CitizenAccountResponseHeaderType
    {
        
        /// <remarks/>
        public CitizenAccountRequestHeaderType RequestHeader;
        
        /// <remarks/>
        public System.DateTime Timestamp;
        
        /// <remarks/>
        public string Status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.0.0.7070-dce2df4c")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.scottishcitizen.gov.uk/service")]
    public partial class CitizenAccountResponseType
    {
        
        /// <remarks/>
        public CitizenAccountResponseHeaderType Header;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.0.0.7070-dce2df4c")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.scottishcitizen.gov.uk/service")]
    public partial class CitizenAccountResponseMessage
    {
        
        /// <remarks/>
        public CitizenAccountResponseType CASResponseData;
    }
}
